name: Chris Odom
favicon: null
layout_spectrum: 0.11521279043518007
typography_spectrum: 0.2460536495782435
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.27665730309672654
  lightness: 0.19528791797347367
  saturation: 0.010264038573950529
  rhythmicContrast: 0.9316683621145785
purpose: []
